controller_manager:
  ros__parameters:
    # Controlador del brazo servo
    arm_controller:
      type: "robot_bombero_controller::ArmServoController"
      joints:
        - "joint_waist"
        - "joint_shoulder"
        - "joint_elbow"
        - "joint_wrist"
      update_rate: 50  # Tasa de actualización en Hz

    # Controlador mecanum para locomoción
    mecanum_controller:
      type: "robot_bombero_controller::MecanumController"
      wheels:
        - "link_fl_wheel_joint"
        - "link_fr_wheel_joint"
        - "link_rl_wheel_joint"
        - "link_rr_wheel_joint"
      update_rate: 50  # Tasa de actualización en Hz
